# Generated by Django 5.2.4 on 2026-07-11 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_newsletterpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletterpage',
            name='list_name',
            field=models.CharField(blank=True, default='Newsletter', help_text='Mailblast contact list to add subscribers to. Defaults to "Newsletter"; clear it only to fall back to the server\'s default list.', max_length=200),
        ),
    ]
