# Generated by Django 5.2.4 on 2025-08-15 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogpages', '0002_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='body',
        ),
    ]
