"""
Django settings for bradrice project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

if os.environ.get('DJANGO_ENV') == 'production':
    load_dotenv(dotenv_path='.env.production')
else:
    load_dotenv(dotenv_path='.env.development')


# Build paths inside the project like this: BASE_DIR / "subdir".
BASE_DIR = Path(__file__).resolve().parent.parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/


# A list of people who get error notifications.
ADMINS = [
    ("Administrator", "bradrice1@gmail.com"),
]


# Application definition

INSTALLED_APPS = [
    # This project
    "website",
    "custom_media",
    "custom_user",
    "payments.apps.PaymentsConfig",
    "figures",
    "blogpages",
    "anymail",
    'wagtailcaptcha',
    'captcha',
    # Wagtail CRX (CodeRed Extensions)
    "coderedcms",
    "django_bootstrap5",
    "modelcluster",
    "taggit",
    "wagtailcache",
    "wagtailseo",
    # Wagtail
    "wagtail.contrib.forms",
    "wagtail.contrib.redirects",
    "wagtail.embeds",
    "wagtail.sites",
    "wagtail.users",
    "wagtail.snippets",
    "wagtail.documents",
    "wagtail.images",
    "wagtail.search",
    "wagtail",
    "wagtail.contrib.settings",
    "wagtail.contrib.table_block",
    "wagtail.admin",
    # Django
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sitemaps",
]

MIDDLEWARE = [
    # Save pages to cache. Must be FIRST.
    "wagtailcache.cache.UpdateCacheMiddleware",
    # Common functionality
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.common.CommonMiddleware",
    # Security
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    # CMS functionality
    "wagtail.contrib.redirects.middleware.RedirectMiddleware",
    # Fetch from cache. Must be LAST.
    "wagtailcache.cache.FetchFromCacheMiddleware",
]

ROOT_URLCONF = "bradrice.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "wagtail.contrib.settings.context_processors.settings",
            ],
        },
    },
]

WSGI_APPLICATION = "bradrice.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
        # WAL mode: readers don't block the writer (and vice versa), and
        # busy_timeout makes a writer wait rather than erroring "database is
        # locked". Requires Django >= 5.1 for SQLite init_command.
        # busy_timeout is 20s (not 5s): under WAL there is still a single
        # writer, and on this RAM-tight box a writer can briefly stall past 5s
        # (swap), which surfaced as intermittent "database is locked" 500s when
        # saving pages in the admin. 20s lets the contending write wait it out.
        # "timeout" mirrors this at the sqlite3.connect level so it applies
        # regardless of init_command ordering.
        #
        # The timeouts above are necessary but not sufficient, because they
        # only govern waiting. Django begins a transaction with a bare "BEGIN"
        # unless transaction_mode is set, and a bare BEGIN is DEFERRED: the
        # transaction takes its read snapshot on the first SELECT and only
        # tries to take the write lock on the first INSERT/UPDATE. If another
        # connection committed in between, that upgrade fails with
        # SQLITE_BUSY_SNAPSHOT *immediately* -- SQLite deliberately does not
        # invoke the busy handler, because waiting cannot resolve it (the
        # transaction would have to abandon the snapshot it already read
        # from). So busy_timeout is bypassed entirely and the request 500s
        # with "database is locked" no matter how high the timeout goes.
        #
        # This is what kept happening on /admin/pages/.../preview/ for newly
        # added artwork: rendering a preview generates image renditions, and a
        # rendition that does not exist yet is *written* to the database, so
        # the read-heavy preview render turns into a write partway through --
        # the exact read-then-upgrade shape above. Existing artwork already
        # has its renditions cached, so previewing it never writes and never
        # trips this, which is why only new pieces failed.
        #
        # BEGIN IMMEDIATE takes the write lock up front, so contention becomes
        # an ordinary wait governed by busy_timeout instead of an instant
        # error. Requires Django >= 5.1.
        "OPTIONS": {
            "timeout": 20,
            "transaction_mode": "IMMEDIATE",
            "init_command": (
                "PRAGMA journal_mode=WAL;"
                "PRAGMA synchronous=NORMAL;"
                "PRAGMA busy_timeout=20000;"
            ),
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

AUTH_USER_MODEL = "custom_user.User"


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "America/New_York"

USE_I18N = False

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATICFILES_FINDERS = [
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
]

STATIC_ROOT = BASE_DIR / "static"
STATIC_URL = "/static/"

MEDIA_ROOT = BASE_DIR / "media"
MEDIA_URL = "/media/"


# Login

LOGIN_URL = "wagtailadmin_login"
LOGIN_REDIRECT_URL = "wagtailadmin_home"


# Wagtail settings

WAGTAIL_SITE_NAME = "Brad Rice"

WAGTAIL_ENABLE_UPDATE_CHECK = False

WAGTAILIMAGES_IMAGE_MODEL = "custom_media.CustomImage"

WAGTAILDOCS_DOCUMENT_MODEL = "custom_media.CustomDocument"

WAGTAILIMAGES_EXTENSIONS = ["gif", "jpg", "jpeg", "png", "webp", "svg"]

# Base URL to use when referring to full URLs within the Wagtail admin backend -
# e.g. in notification emails. Don't include '/admin' or a trailing slash
WAGTAILADMIN_BASE_URL = "http://bradrice.com"

#anymail

EMAIL_BACKEND = "anymail.backends.mailgun.EmailBackend"
DEFAULT_FROM_EMAIL = "brad@bradrice.com"
SERVER_EMAIL = "admin@oh-joy.org"
MANAGERS = ADMINS
ANYMAIL = {
    "MAILGUN_API_KEY": os.getenv("MAILGUN_API_KEY"),
    "MAILGUN_SENDER_DOMAIN": "mail.oh-joy.org",
}

# Email address used to send error messages to ADMINS.
SERVER_EMAIL = DEFAULT_FROM_EMAIL


# Mailblast subscribe API (newsletter signup form -> mailblast /api/subscribe/).
# Set both in .env.development / .env.production. Blank = signup disabled (the
# form shows a friendly "temporarily unavailable" message rather than erroring).
MAILBLAST_API_URL = os.getenv("MAILBLAST_API_URL", "")
MAILBLAST_API_KEY = os.getenv("MAILBLAST_API_KEY", "")


# Tags

TAGGIT_CASE_INSENSITIVE = True


# Sets default for primary key IDs
# See https://docs.djangoproject.com/en/5.2/ref/models/fields/#bigautofield
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# Disable built-in CRX Navbar and Footer since this project has a
# custom implementation.
CRX_DISABLE_NAVBAR = True
CRX_DISABLE_FOOTER = True


# Stripe API version, pinned deliberately rather than left to the account
# default. Two reasons it is set here and not in the environment: it is not a
# secret, and it belongs with the code that was written against it — changing
# it should be a reviewed commit, not an unlogged edit to a file on the server.
#
# The account default is still 2020-08-27. stripe-python 8.0.0 and later stop
# deferring to the account default and send the version they were built for, so
# upgrading the SDK moves the API version whether or not you intend it. Naming
# it here means the version in use is whatever this line says, independent of
# both the account setting and the installed SDK.
#
# Keep this in step with the pinned `stripe` release in requirements.txt.
STRIPE_API_VERSION = "2026-07-29.dahlia"

