# Generated by Django 5.2.1 on 2025-07-11 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('figures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='figuredetail',
            name='for_sale',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='figuredetail',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default='20.00', max_digits=10),
        ),
        migrations.AddField(
            model_name='figuredetail',
            name='stripe_price_id',
            field=models.CharField(blank=True),
        ),
    ]
