# Generated by Django 5.2.1 on 2025-07-11 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('figures', '0002_figuredetail_for_sale_figuredetail_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='figuredetail',
            name='stripe_price_id',
            field=models.CharField(blank=True, default='price_1HQCTSHr3XrGP7sjsQHxXSJv'),
        ),
    ]
