# Generated by Django 5.2.4 on 2025-07-30 19:23

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('figures', '0003_alter_figuredetail_stripe_price_id'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='figuredetail',
            name='stripe_price_id',
            field=models.CharField(blank=True, default=None),
        ),
        migrations.CreateModel(
            name='MyPageGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(blank=True, max_length=250)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='figures.figuredetail')),
            ],
        ),
    ]
