# Generated by Django 5.2.4 on 2025-07-31 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_media', '0001_initial'),
        ('figures', '0004_alter_figuredetail_stripe_price_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mypagegalleryimage',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='custom_media.customimage'),
        ),
    ]
