# Generated by Django 5.2.4 on 2025-08-07 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('figures', '0006_alter_figuredetail_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='figuredetail',
            name='sold',
            field=models.BooleanField(default=False),
        ),
    ]
