# Generated by Django 5.2.4 on 2025-08-19 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('figures', '0007_figuredetail_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='figuredetail',
            name='media',
            field=models.CharField(choices=[('Acrylic', 'Acrylic'), ('Oil', 'Oil'), ('Watercolor', 'Watercolor'), ('Print', 'Print'), ('Graphite', 'Graphite'), ('Pastel', 'Pastel')], default='Acrylic', max_length=24),
        ),
    ]
