# Generated by Django 5.2.4 on 2025-08-22 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('figures', '0008_figuredetail_media'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='figuredetail',
            name='media_type',
        ),
    ]
