# Generated by Django 5.2.4 on 2025-08-22 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('figures', '0008_figuredetail_media'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='figuredetail',
            name='media_type',
        ),
        migrations.AlterField(
            model_name='figuredetail',
            name='media',
            field=models.CharField(choices=[('Acrylic', 'Acrylic'), ('Oil', 'Oil'), ('Watercolor', 'Watercolor'), ('Print', 'Print'), ('Graphite', 'Graphite'), ('Pastel', 'Pastel')], default=None, max_length=24, null=True, blank=True),
        ),
    ]
