# Generated by Django 5.2.4 on 2025-08-22 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('figures', '0009_remove_figuredetail_media_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='figureindex',
            name='media',
            field=models.CharField(choices=[('Acrylic', 'Acrylic'), ('Oil', 'Oil'), ('Watercolor', 'Watercolor'), ('Print', 'Print'), ('Graphite', 'Graphite'), ('Pastel', 'Pastel')], default=None, max_length=24, null=True, blank=True),
        ),
    ]
