# Generated by Django 5.2.4 on 2025-08-22 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('figures', '0009_remove_figuredetail_media_type_and_more'),
    ]

    operations = [
    ]
