# Generated by Django 5.2.4 on 2025-11-14 15:58

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('figures', '0010_figureindex_media'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeriesName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Series Name',
                'verbose_name_plural': 'Series Names',
            },
        ),
        migrations.AlterField(
            model_name='figuredetail',
            name='media',
            field=models.CharField(choices=[('Acrylic', 'Acrylic'), ('Oil', 'Oil'), ('Watercolor', 'Watercolor'), ('Print', 'Print'), ('Graphite', 'Graphite'), ('Pastel', 'Pastel')], default=None, max_length=24),
        ),
        migrations.CreateModel(
            name='MyPageSnippetOrderable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='series_type', to='figures.figuredetail')),
                ('snippet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='figures.seriesname')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
