# Generated by Django 5.2.4 on 2025-11-19 16:24

from decimal import Decimal

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('figures', '0011_seriesname_remove_figureindex_media_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaSnippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Media Snippet',
                'verbose_name_plural': 'Media Snippets',
            },
        ),
        migrations.AlterField(
            model_name='figuredetail',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('20'), max_digits=10),
        ),
        migrations.AddField(
            model_name='figuredetail',
            name='media_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='figures.mediasnippet'),
        ),
    ]
