# Generated by Django 5.2.4 on 2025-11-21 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('figures', '0012_mediasnippet_remove_figuredetail_media_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='figuredetail',
            name='media',
        ),
        migrations.AlterField(
            model_name='mediasnippet',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
