# Generated by Django 5.2.4 on 2026-02-23 21:37

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('figures', '0013_remove_figureindex_media_alter_figuredetail_media_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='figuredetail',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('200'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='figuredetail',
            name='weight',
            field=models.IntegerField(default=10, help_text='Lower number means higher priority in sorting.'),
        ),
    ]
