# Generated by Django 5.2.4 on 2026-05-08 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('figures', '0014_alter_figuredetail_price_alter_figuredetail_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='figuredetail',
            name='height',
            field=models.FloatField(blank=True, help_text='Height in inches', null=True),
        ),
        migrations.AddField(
            model_name='figuredetail',
            name='width',
            field=models.FloatField(blank=True, help_text='Width in inches', null=True),
        ),
    ]
