# Generated by Django 5.2.4 on 2026-07-11 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('figures', '0015_figuredetail_height_figuredetail_width'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='figuredetail',
            name='stripe_price_id',
        ),
        migrations.AlterField(
            model_name='figuredetail',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default='0.00', max_digits=10),
        ),
        migrations.AlterField(
            model_name='figuredetail',
            name='weight',
            field=models.IntegerField(default=0, help_text='Lower number means higher priority in sorting.'),
        ),
    ]
