# Generated by Django 5.2.4 on 2026-07-13 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('figures', '0016_remove_figuredetail_stripe_price_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='figuredetail',
            options={'ordering': ['weight', '-first_published_at']},
        ),
        migrations.AlterField(
            model_name='figuredetail',
            name='weight',
            field=models.IntegerField(default=100000, help_text='Sort priority — lower floats to the front. Leave at the default and the image sorts with the newest; set a low number (e.g. 10, 20, 30) to pin it toward the top.'),
        ),
    ]
