# Generated by Django 5.2.17 on 2026-08-31 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_media', '0001_initial'),
        ('figures', '0017_alter_figuredetail_options_alter_figuredetail_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='figuredetail',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='custom_media.customimage'),
        ),
    ]
