# Generated by Django 5.2.17 on 2026-09-01 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('figures', '0018_alter_figuredetail_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='figuredetail',
            name='date_painted',
            field=models.DateField(blank=True, help_text='When the piece was painted. Only the month and year are shown on the page. Leave blank if unknown.', null=True),
        ),
    ]
