# Generated by Django 5.2.17 on 2026-09-09 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('figures', '0019_figuredetail_date_painted'),
    ]

    operations = [
        migrations.AddField(
            model_name='figuredetail',
            name='hide_from_index',
            field=models.BooleanField(default=False, help_text='Keep this piece off the Artwork gallery. It stays published and reachable by direct link.'),
        ),
    ]
